#!/bin/bash
#-----------------------------------------------------------------------------------------------------------------------
# git pre-commit hooks
#
# To install this and other hooks, run:
#
#   for-each.sh active-repos git init --template=${ROOT}/phet-info/git-template-dir
#
# ... where ${ROOT} is the parent directory for your local copy of PhET repos.
#
# This and other hooks may use grunt, so you will also need to 'npm install' for active-repos.
#
# git init does not overwrite files, so you may need to clear existing precommit hooks with a command like:
#
#    for-each.sh active-repos rm .git/hooks/pre-commit
#
#-----------------------------------------------------------------------------------------------------------------------

# If the repo has a Gruntfile.js, then it should support lint.
if [ -f "Gruntfile.js" ]
then
  grunt lint
fi
