#!/bin/bash
#-----------------------------------------------------------------------------------------------------------------------
# git pre-commit hooks
#
# Please see https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#utilities-and-instrumentation-for-development-and-testing
# for installation instructions.
#-----------------------------------------------------------------------------------------------------------------------

node ../chipper/js/scripts/hook-pre-commit.js
